/**
 * Rewrites the adaptive-icon descriptors after @capacitor/assets has produced
 * the density PNGs.
 *
 * Two things the generator gets wrong for this app:
 *   1. it wraps both layers in a 16.7% <inset>, which shrinks a mark that is
 *      already sized for the safe zone and leaves the icon looking lost;
 *   2. it never emits a <monochrome> layer, so Android 13+ themed icons fall
 *      back to a washed-out crop of the colour icon.
 *
 *   node scripts/adaptive-icon.mjs        (or: npm run assets)
 */
import { writeFile } from "node:fs/promises";

const DIR = "android/app/src/main/res/mipmap-anydpi-v26";

const NOTE = `<!-- Generated by scripts/adaptive-icon.mjs — do not hand-edit.
     No <inset>: resources/icon-foreground.png already holds the mark at 47%
     of the canvas, inside the 66% every launcher mask is guaranteed to show. -->`;

const layers = `    <background android:drawable="@mipmap/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />`;

for (const name of ["ic_launcher.xml", "ic_launcher_round.xml"]) {
  await writeFile(
    `${DIR}/${name}`,
    `<?xml version="1.0" encoding="utf-8"?>
${NOTE}
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
${layers}
</adaptive-icon>
`
  );
  console.log("wrote", `${DIR}/${name}`);
}
