/**
 * Renders the app icon and splash sources that @capacitor/assets consumes.
 * Everything is derived from public/icon.svg so the APK, the PWA and the
 * landing page keep showing the same mark.
 *
 *   node scripts/make-assets.mjs
 */
import { mkdir, writeFile } from "node:fs/promises";
import sharp from "sharp";

const NAVY = "#1a1e26";
const PAPER = "#fafaf7";
const INK_DARK = "#14171e";
const RULE = "#c9ccc4";

/** The page-with-a-dog-ear glyph, drawn in the source SVG's 512 grid.
    `outlined` adds the hairline the sheet needs when it sits on paper rather
    than on the navy plate — without it the light splash is an invisible white
    sheet on a white field. Same weight as the 1px border on a library card. */
const glyph = (outlined = false) => `
  <path d="M128 112h192l64 64v224H128z" fill="${PAPER}"${
  outlined ? ` stroke="${RULE}" stroke-width="6"` : ""
}/>
  <path d="M320 112l64 64h-64z" fill="#f5d547"/>
  <rect x="160" y="232" width="192" height="18" rx="9" fill="${RULE}"/>
  <rect x="160" y="278" width="192" height="18" rx="9" fill="${RULE}"/>
  <rect x="160" y="324" width="128" height="18" rx="9" fill="#f5d547"/>`;

/** Glyph bounding box inside that 512 grid. */
const BOX = { x: 128, y: 112, w: 256, h: 288 };

/** Place the glyph on a `size` canvas so its height covers `heightRatio`. */
function centeredGlyph(size, heightRatio, outlined = false) {
  const scale = (size * heightRatio) / BOX.h;
  const tx = (size - BOX.w * scale) / 2 - BOX.x * scale;
  const ty = (size - BOX.h * scale) / 2 - BOX.y * scale;
  return `<g transform="translate(${tx} ${ty}) scale(${scale})">${glyph(
    outlined
  )}</g>`;
}

function svg(size, body, background) {
  const bg = background
    ? `<rect width="${size}" height="${size}" fill="${background}"/>`
    : "";
  return Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">${bg}${body}</svg>`
  );
}

// The SVG already carries its pixel size, so the raised density would scale it
// a second time — resize back down to the size we asked for. The mark is five
// flat colours, so a palette PNG is both smaller and lossless.
const render = (buf, size, out) =>
  sharp(buf, { density: 288 })
    .resize(size, size)
    .png({ palette: true, compressionLevel: 9 })
    .toFile(out);

await mkdir("resources", { recursive: true });

// Legacy square icon: rounded navy tile, same proportions as the 512 source.
await render(
  svg(
    1024,
    `<rect width="1024" height="1024" rx="192" fill="${NAVY}"/>${centeredGlyph(
      1024,
      0.5625
    )}`
  ),
  1024,
  "resources/icon.png"
);

// Adaptive icon. Android masks the outer third away, so the glyph stays
// inside the safe circle and the background is a flat navy plate.
await render(
  svg(1024, centeredGlyph(1024, 0.47)),
  1024,
  "resources/icon-foreground.png"
);
await render(svg(1024, "", NAVY), 1024, "resources/icon-background.png");

// Splash: one calm mark on the app's own paper / ink background.
await render(
  svg(2732, centeredGlyph(2732, 0.135, true), PAPER),
  2732,
  "resources/splash.png"
);
await render(
  svg(2732, centeredGlyph(2732, 0.135), INK_DARK),
  2732,
  "resources/splash-dark.png"
);

// Keep the in-app PNGs in step with the same source.
for (const [size, file] of [
  [512, "public/icon-512.png"],
  [192, "public/icon-192.png"],
  [192, "app/icon.png"],
]) {
  await render(
    svg(
      size,
      `<rect width="${size}" height="${size}" rx="${
        size * 0.1875
      }" fill="${NAVY}"/>${centeredGlyph(size, 0.5625)}`
    ),
    size,
    file
  );
}

await writeFile(
  "resources/README.md",
  "Generated by `node scripts/make-assets.mjs` from `public/icon.svg`.\n" +
    "Do not hand-edit; change the SVG or the script instead, then re-run\n" +
    "`npx @capacitor/assets generate --android`.\n"
);

console.log("assets written");
